### ISSUE TITLE
Тайтл

### ISSUE THREAD

**Issue by oxxxxxy** [repair-cat/DKPV_imitator#1]
ЗДарова, а чо, для чего это? Мб, знаешь, где самодельные ЭБУ делают ребята? Или какой форум подскажешь, где энтузиасты автомобильное что-то проектируют, реализуют, кодят и т.д.? Пабрацки, оч прошу да.

**Comment by oxxxxxy** [comment]
мб, кольцевики какие, гхонщики нелегальные и т.д.

**Comment by oxxxxxy** [comment]
шалом

**Comment by oxxxxxy** [comment]
умерчик, да?

**Comment by oxxxxxy** [comment]
pohuy, davay udachi

**Comment by are-nic** [comment]
@oxxxxxy привет. Это для имитации работы двигателя для ЭБУ. Чтобы можно было мозги ковырять без установки в автомобиле. так удобнее. На счет форумов и проего не в курсе.

**Comment by oxxxxxy** [comment]
Блин, хорошая идея, спасибо. ❤️❤️❤️

**Comment by oxxxxxy** [comment]
Да и извини, если я там некорректно повел себя, да.
